Play_Permission: false #If set to true, players will need the speedrunnervshunter.player permission to be able to play a Speedrunner VS Hunter Game
OffGameProtection:
  Disable_Player_Damages: true
  Disable_Entity_Damages: true
  Disable_Player_Targets: true
  Disable_Entity_Targets: true
  Disable_Loosing_Food: true
  Disable_DayLight_Cycle: true
  Disable_Block_Place: true
  Disable_Block_Break: true
  Disable_OpenChest: true
  Disable_Item_Drop: true
  StartWorldBorder: SpawnRadiusGamerule #Set to -1 to disable or set to SpawnRadiusGamerule to base the border size on your SpawnRadius Gamerule Value
  WorldStartTime: 51 #Set to -1 to disable
GameOptions:
  SpeedRunnersBecomesHuntersAtDeath: false
  #If the option above is set to false, the option below will be checked
  SpectatorAfterSpeedRunnerRealDeath: true