name: SpeedRunnerVSHunter
author: DarkBow_
version: 1.6
main: fr.darkbow_.speedrunnervshunter.SpeedRunnerVSHunter
commands:
  speedrunnervshunter:
    description: SpeedRunnerVSHunter Plugin
    permission:
    aliases: [svh, speedrunner, srvsh]
api-version: 1.16